version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "${EXTERNAL_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:


networks:
  default:
    name: ${NETWORK:-postgres_network}
    driver: bridge
